# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/example_design/sem_0_sem_example.xdc

# Block Designs: bd/ps_0/ps_0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_0 || ORIG_REF_NAME==ps_0}]

# IP: bd/ps_0/ip/ps_0_processing_system7_0_0/ps_0_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_0_processing_system7_0_0 || ORIG_REF_NAME==ps_0_processing_system7_0_0}]

# IP: bd/ps_0/ip/ps_0_axi_gpio_0_0/ps_0_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_0_axi_gpio_0_0 || ORIG_REF_NAME==ps_0_axi_gpio_0_0}]

# IP: bd/ps_0/ip/ps_0_processing_system7_0_axi_periph_0/ps_0_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_0_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==ps_0_processing_system7_0_axi_periph_0}]

# IP: bd/ps_0/ip/ps_0_rst_processing_system7_0_102M_0/ps_0_rst_processing_system7_0_102M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_0_rst_processing_system7_0_102M_0 || ORIG_REF_NAME==ps_0_rst_processing_system7_0_102M_0}]

# IP: bd/ps_0/ip/ps_0_auto_pc_0/ps_0_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_0_auto_pc_0 || ORIG_REF_NAME==ps_0_auto_pc_0}]

# XDC: bd/ps_0/ip/ps_0_processing_system7_0_0/ps_0_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_0_processing_system7_0_0 || ORIG_REF_NAME==ps_0_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/ps_0/ip/ps_0_axi_gpio_0_0/ps_0_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_0_axi_gpio_0_0 || ORIG_REF_NAME==ps_0_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_0/ip/ps_0_axi_gpio_0_0/ps_0_axi_gpio_0_0_ooc.xdc

# XDC: bd/ps_0/ip/ps_0_axi_gpio_0_0/ps_0_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_0_axi_gpio_0_0 || ORIG_REF_NAME==ps_0_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_0/ip/ps_0_rst_processing_system7_0_102M_0/ps_0_rst_processing_system7_0_102M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_0_rst_processing_system7_0_102M_0 || ORIG_REF_NAME==ps_0_rst_processing_system7_0_102M_0}]

# XDC: bd/ps_0/ip/ps_0_rst_processing_system7_0_102M_0/ps_0_rst_processing_system7_0_102M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_0_rst_processing_system7_0_102M_0 || ORIG_REF_NAME==ps_0_rst_processing_system7_0_102M_0}]

# XDC: bd/ps_0/ip/ps_0_rst_processing_system7_0_102M_0/ps_0_rst_processing_system7_0_102M_0_ooc.xdc

# XDC: bd/ps_0/ip/ps_0_auto_pc_0/ps_0_auto_pc_0_ooc.xdc

# XDC: bd/ps_0/ps_0_ooc.xdc
