# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.cache/wt [current_project]
set_property parent.project_path C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files -quiet C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.runs/sem_0_sem_vio_synth_1/sem_0_sem_vio.dcp
set_property used_in_implementation false [get_files C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.runs/sem_0_sem_vio_synth_1/sem_0_sem_vio.dcp]
add_files -quiet C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.runs/sem_0_synth_1/sem_0.dcp
set_property used_in_implementation false [get_files C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.runs/sem_0_synth_1/sem_0.dcp]
add_files C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/bd/ps_0/ps_0.bd
set_property used_in_implementation false [get_files -all c:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/bd/ps_0/ip/ps_0_processing_system7_0_0/ps_0_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/bd/ps_0/ip/ps_0_axi_gpio_0_0/ps_0_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/bd/ps_0/ip/ps_0_axi_gpio_0_0/ps_0_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/bd/ps_0/ip/ps_0_axi_gpio_0_0/ps_0_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/bd/ps_0/ip/ps_0_rst_processing_system7_0_102M_0/ps_0_rst_processing_system7_0_102M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/bd/ps_0/ip/ps_0_rst_processing_system7_0_102M_0/ps_0_rst_processing_system7_0_102M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/bd/ps_0/ip/ps_0_rst_processing_system7_0_102M_0/ps_0_rst_processing_system7_0_102M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/bd/ps_0/ip/ps_0_auto_pc_0/ps_0_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/bd/ps_0/ps_0_ooc.xdc]
set_property is_locked true [get_files C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/bd/ps_0/ps_0.bd]

read_vhdl -library xil_defaultlib {
  C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/imports/example_design/sem_0_sem_mon_sipo.vhd
  C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/imports/example_design/sem_0_sem_mon_piso.vhd
  C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/imports/example_design/sem_0_sem_mon_fifo.vhd
  C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/imports/example_design/sem_0_sem_mon.vhd
  C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/imports/example_design/sem_0_sem_hid.vhd
  C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/imports/example_design/sem_0_sem_cfg.vhd
  C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/imports/hdl/ps_0_wrapper.vhd
}
read_xdc C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/constrs_1/imports/example_design/sem_0_sem_example.xdc
set_property used_in_implementation false [get_files C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/constrs_1/imports/example_design/sem_0_sem_example.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top ps_0_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef ps_0_wrapper.dcp
catch { report_utilization -file ps_0_wrapper_utilization_synth.rpt -pb ps_0_wrapper_utilization_synth.pb }
