# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/ip/sem_0/sem_0.xci
# IP: The module: 'sem_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/ip/sem_0/synth/sem_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sem_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/ip/sem_0/sem_0.xci
# IP: The module: 'sem_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tambara/Desktop/zynq_scrubbing/sem_v1/sem_0_example/sem_0_example.srcs/sources_1/ip/sem_0/synth/sem_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sem_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
